project_id = "qxtviztoorgomfkerndj"

[functions.save-google-calendar-token]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.trigger-onboarding]
verify_jwt = false
